In [1]:
import torch

In [2]:
# 创建一个包含 0 到 11 的一维张量
x = torch.arange(12)  
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 查看张量的形状
x.shape

torch.Size([12])

In [4]:
# 获取张量中元素的总数
x.numel()

12

In [5]:
# 将一维张量重塑为 3 行 4 列的二维张量
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4)) # 创建一个形状为 (2,3,4) 的全零张量

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4)) # 创建一个形状为 (2,3,4) 的全一张量

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]) # 从嵌套列表直接创建张量

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [9]:
x = torch.tensor([1.0,2,4,6])
y = torch.tensor([3,3,3,3])
x + y, x - y, x * y, x / y,x**y #**是求幂运算

(tensor([4., 5., 7., 9.]),
 tensor([-2., -1.,  1.,  3.]),
 tensor([ 3.,  6., 12., 18.]),
 tensor([0.3333, 0.6667, 1.3333, 2.0000]),
 tensor([  1.,   8.,  64., 216.]))

In [10]:
torch.exp(x) #指数运算

tensor([  2.7183,   7.3891,  54.5981, 403.4288])

In [11]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1) # 拼接张量，dim=0 按行拼接，dim=1 按列拼接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
X.sum()

tensor(66.)

In [14]:
# 创建两个不同形状的张量，用于广播机制演示
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [16]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [17]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [19]:
# 原地操作：创建与Y形状相同的零张量，然后修改其值，id不变
Z = torch.zeros_like(Y)  
print('id(Z):', id(Z))  
Z[:] = X + Y         
print('id(Z):', id(Z))

id(Z): 1881512387648
id(Z): 1881512387648


In [20]:
before = id (X)
X += Y
id(X) == before

True

In [21]:
# 张量与NumPy数组的相互转换
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [22]:
# 将单元素张量转换为Python标量
a = torch.tensor([4.5])
a,a.item(),float(a),int(a)

(tensor([4.5000]), 4.5, 4.5, 4)