In [1]:
import torch

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)  #等价于'x =torch.arange(4.0,requires_grad=True)'
x.grad #默认值是None

In [5]:
y = 2*torch.dot(x,x) 
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward() # 反向传播求梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x # 验证梯度是否正确

tensor([True, True, True, True])

In [8]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [9]:
# 再次清零，对 y = x*x 逐元素求导
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [10]:
# 使用 detach 分离计算图
x.grad.zero_()
y = x*x
u = y.detach() # u 视为常数，不再记录梯度
z = u*x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [11]:
# 验证 y 的梯度
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [12]:
# python控制流下的自动求导
def f(a):
    b = a*2
    while b.norm() <1000:
        b = b*2
    if b.sum()>0:
        c = b
    else:
        c = 100*b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

# 验证梯度
a.grad == d / a

tensor(True)