In [2]:
import torch
import torch.nn.functional as F
from torch import nn

In [3]:
class CenterredLayer(nn.Module):
    def __init__(self,):
        super().__init__()
    def forward(self,x):
        return x-x.mean()
layer=CenterredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net=nn.Sequential(nn.Linear(8,128),CenterredLayer())
y=net(torch.rand(4,8))
y.mean()

tensor(8.3819e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))  # 修正: in_units
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data  # 修正: weight
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight 

Parameter containing:
tensor([[ 0.2201, -1.0454,  0.2338],
        [-0.6915,  0.3590,  1.1456],
        [-0.8941,  1.1096, -0.9519],
        [-0.3131,  1.1317, -0.7355],
        [ 1.1099, -0.5319,  0.6832]], requires_grad=True)

In [6]:
dense(torch.rand(2,5))

tensor([[0.8260, 1.8983, 0.0000],
        [0.7153, 1.1621, 0.6889]])

In [11]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[8.2637],
        [3.1158]])